import { Routes } from '@angular/router';
import { authGuard } from './core/guards/auth.guard';
import { permissionGuard } from './core/guards/permission.guard';

export const routes: Routes = [
  { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
  { path: 'login', loadComponent: () => import('./features/auth/login/login.component').then(m => m.LoginComponent) },
  {
    path: 'dashboard',
    canActivate: [authGuard],
    loadComponent: () => import('./layout/dashboard-layout/dashboard-layout.component').then(m => m.DashboardLayoutComponent),
    children: [
      { path: '', redirectTo: 'home', pathMatch: 'full' },
      { path: 'home', loadComponent: () => import('./features/dashboard/dashboard.component').then(m => m.DashboardComponent) },
      { path: 'pos', canActivate: [permissionGuard('pos.view')], loadComponent: () => import('./features/pos/pos.component').then(m => m.PosComponent) },
      { path: 'orders', loadComponent: () => import('./features/orders/orders-list/orders-list.component').then(m => m.OrdersListComponent) },
      { path: 'guides', loadComponent: () => import('./features/guides/guides-list/guides-list.component').then(m => m.GuidesListComponent) },
      { path: 'guides/new', loadComponent: () => import('./features/orders/order-form/order-form.component').then(m => m.OrderFormComponent), data: { guideMode: true, backRoute: '/dashboard/guides' } },
      { path: 'guides/:id', loadComponent: () => import('./features/orders/order-form/order-form.component').then(m => m.OrderFormComponent), data: { guideMode: true, backRoute: '/dashboard/guides' } },
      { path: 'orders/new', loadComponent: () => import('./features/orders/order-form/order-form.component').then(m => m.OrderFormComponent) },
      { path: 'orders/:id', loadComponent: () => import('./features/orders/order-form/order-form.component').then(m => m.OrderFormComponent) },
      { path: 'inventory', loadComponent: () => import('./features/inventory/inventory-list/inventory-list.component').then(m => m.InventoryListComponent) },
      { path: 'stock', loadComponent: () => import('./features/stock/stock-list/stock-list.component').then(m => m.StockListComponent) },
      { path: 'stock/new', loadComponent: () => import('./features/stock/stock-form/stock-form.component').then(m => m.StockFormComponent) },
      { path: 'stock/transfer', loadComponent: () => import('./features/stock/stock-transfer/stock-transfer.component').then(m => m.StockTransferComponent) },
      { path: 'stock/:id', loadComponent: () => import('./features/stock/stock-form/stock-form.component').then(m => m.StockFormComponent) },
      { path: 'customers', loadComponent: () => import('./features/customers/customers-list/customers-list.component').then(m => m.CustomersListComponent) },
      { path: 'customers/new', loadComponent: () => import('./features/customers/customer-form/customer-form.component').then(m => m.CustomerFormComponent) },
      { path: 'customers/:id', loadComponent: () => import('./features/customers/customer-form/customer-form.component').then(m => m.CustomerFormComponent) },
      // { path: 'sales', loadComponent: () => import('./features/reports/sales-import/sales-import.component').then(m => m.SalesImportComponent) },
      { path: 'sales', canActivate: [permissionGuard('sales.view')], loadComponent: () => import('./features/sales/sales-list/sales-list.component').then(m => m.SalesListComponent) },
      { path: 'sales/new', loadComponent: () => import('./features/sales/sale-form/sale-form.component').then(m => m.SaleFormComponent) },
      { path: 'sales/:id', loadComponent: () => import('./features/sales/sale-form/sale-form.component').then(m => m.SaleFormComponent) },
      { path: 'promotions', canActivate: [permissionGuard('promotions.view')], loadComponent: () => import('./features/promotions/promotions-list/promotions-list.component').then(m => m.PromotionsListComponent) },
      { path: 'promotions/new', loadComponent: () => import('./features/promotions/promotion-form/promotion-form.component').then(m => m.PromotionFormComponent) },
      { path: 'promotions/:id', loadComponent: () => import('./features/promotions/promotion-form/promotion-form.component').then(m => m.PromotionFormComponent) },
      { path: 'users', loadComponent: () => import('./features/users/users-list/users-list.component').then(m => m.UsersListComponent) },
      { path: 'users/new', loadComponent: () => import('./features/users/user-form/user-form.component').then(m => m.UserFormComponent) },
      { path: 'users/:id', loadComponent: () => import('./features/users/user-form/user-form.component').then(m => m.UserFormComponent) },
      { path: 'settings', loadComponent: () => import('./features/settings/settings/settings.component').then(m => m.SettingsComponent) },
      { path: 'settings/roles', loadComponent: () => import('./features/settings/roles-list/roles-list.component').then(m => m.RolesListComponent) },
      { path: 'settings/order-statuses',   loadComponent: () => import('./features/settings/config-crud/config-crud.component').then(m => m.ConfigCrudComponent), data: { endpoint: 'order-statuses',   icon: 'bi-tag',         title: 'Estados de pedido', searchEnabled: true, serverPagination: true, perPage: 10, searchPlaceholder: 'Buscar por nombre o slug…', columns: [{ key: 'name', label: 'Nombre' }, { key: 'slug', label: 'Slug', type: 'slug' }, { key: 'color', label: 'Color', type: 'color' }] } },
      { path: 'settings/shipping-agencies',loadComponent: () => import('./features/settings/config-crud/config-crud.component').then(m => m.ConfigCrudComponent), data: { endpoint: 'shipping-agencies', icon: 'bi-truck',        title: 'Agencias de envío', searchEnabled: true, serverPagination: true, perPage: 10, searchPlaceholder: 'Buscar por nombre o código…', columns: [{ key: 'name', label: 'Nombre' }, { key: 'code', label: 'Código' }, { key: 'shipping_rate', label: 'Tarifa de envío (S/)', type: 'number' }] } },
      { path: 'settings/purchase-types',   loadComponent: () => import('./features/settings/config-crud/config-crud.component').then(m => m.ConfigCrudComponent), data: { endpoint: 'purchase-types',   icon: 'bi-cart',         title: 'Tipos de compra',   searchEnabled: true, serverPagination: true, perPage: 10, searchPlaceholder: 'Buscar por nombre o slug…',   columns: [{ key: 'name', label: 'Nombre' }, { key: 'slug', label: 'Slug', type: 'slug' }] } },
      { path: 'settings/product-types',    loadComponent: () => import('./features/settings/config-crud/config-crud.component').then(m => m.ConfigCrudComponent), data: { endpoint: 'product-types',    icon: 'bi-grid',         title: 'Tipos de producto', searchEnabled: true, serverPagination: true, perPage: 10, searchPlaceholder: 'Buscar por nombre o slug…',   columns: [{ key: 'name', label: 'Nombre' }, { key: 'slug', label: 'Slug', type: 'slug' }] } },
      { path: 'settings/colors',           loadComponent: () => import('./features/settings/config-crud/config-crud.component').then(m => m.ConfigCrudComponent), data: { endpoint: 'colors',           icon: 'bi-palette',      title: 'Colores', searchEnabled: true, serverPagination: true, perPage: 12, searchPlaceholder: 'Buscar por nombre, slug o HEX…', columns: [{ key: 'name', label: 'Nombre' }, { key: 'hex_code', label: 'Color', type: 'color' }, { key: 'slug', label: 'Slug', type: 'slug' }] } },
      { path: 'settings/warehouses',       loadComponent: () => import('./features/settings/config-crud/config-crud.component').then(m => m.ConfigCrudComponent), data: { endpoint: 'warehouses', adminOnly: true, icon: 'bi-building', title: 'Almacenes', searchEnabled: true, serverPagination: true, perPage: 12, searchPlaceholder: 'Buscar almacén por nombre o código…', columns: [{ key: 'name', label: 'Nombre' }, { key: 'code', label: 'Código' }, { key: 'address', label: 'Dirección' }, { key: 'city', label: 'Ciudad' }, { key: 'is_pos', label: 'Punto de venta', type: 'boolean' }] } },
      { path: 'settings/warehouse-types',   loadComponent: () => import('./features/settings/config-crud/config-crud.component').then(m => m.ConfigCrudComponent), data: { endpoint: 'warehouse-types',   icon: 'bi-buildings',    title: 'Tipos de almac\u00e9n',  searchEnabled: true, serverPagination: true, perPage: 10, searchPlaceholder: 'Buscar por nombre o c\u00f3digo\u2026',  columns: [{ key: 'name', label: 'Nombre' }, { key: 'code', label: 'C\u00f3digo' }, { key: 'description', label: 'Descripci\u00f3n', type: 'textarea' }] } },
      { path: 'settings/collections',      loadComponent: () => import('./features/settings/config-crud/config-crud.component').then(m => m.ConfigCrudComponent), data: { endpoint: 'collections',      icon: 'bi-collection',   title: 'Colecciones',       searchEnabled: true, serverPagination: true, perPage: 10, searchPlaceholder: 'Buscar por nombre o slug\u2026',    columns: [{ key: 'name', label: 'Nombre' }, { key: 'slug', label: 'Slug', type: 'slug' }] } },
      { path: 'settings/unit-measures',     loadComponent: () => import('./features/settings/config-crud/config-crud.component').then(m => m.ConfigCrudComponent), data: { endpoint: 'unit-measures', icon: 'bi-rulers', title: 'Unidades de medida', searchEnabled: true, serverPagination: true, perPage: 10, searchPlaceholder: 'Buscar por nombre, código o SUNAT…', columns: [{ key: 'name', label: 'Nombre' }, { key: 'code', label: 'Código' }, { key: 'sunat_code', label: 'Código SUNAT' }] } },
      { path: 'settings/provinces',        loadComponent: () => import('./features/settings/geo-settings/geo-settings.component').then(m => m.GeoSettingsComponent) },
      { path: 'settings/fiscal',            loadComponent: () => import('./features/settings/fiscal-settings/fiscal-settings.component').then(m => m.FiscalSettingsComponent) },
      { path: 'settings/payment-methods',   loadComponent: () => import('./features/settings/config-crud/config-crud.component').then(m => m.ConfigCrudComponent), data: { endpoint: 'payment-methods', icon: 'bi-credit-card', title: 'M\u00e9todos de pago', searchEnabled: true, serverPagination: true, perPage: 10, searchPlaceholder: 'Buscar por nombre o c\u00f3digo\u2026', columns: [{ key: 'name', label: 'Nombre' }, { key: 'code', label: 'C\u00f3digo' }] } },
      { path: 'invoices', canActivate: [permissionGuard('invoices.view')], loadComponent: () => import('./features/invoices/invoices-list/invoices-list.component').then(m => m.InvoicesListComponent) },
      { path: 'products',     loadComponent: () => import('./features/products/products-list/products-list.component').then(m => m.ProductsListComponent) },
      { path: 'products/new', loadComponent: () => import('./features/products/product-form/product-form.component').then(m => m.ProductFormComponent) },
      { path: 'products/:id', loadComponent: () => import('./features/products/product-form/product-form.component').then(m => m.ProductFormComponent) },
    ],
  },
  { path: '**', redirectTo: 'dashboard' },
];
