// <auto-generated />
using AdminHiitop.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AdminHiitop.Api.Migrations
{
    [DbContext(typeof(AdminHiitopDbContext))]
    [Migration("20260604000004_MakeOrderItemProductIdNullable")]
    partial class MakeOrderItemProductIdNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Model snapshot is maintained in AdminHiitopDbContextModelSnapshot.cs
        }
    }
}
