// <auto-generated />
using System;
using AdminHiitop.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdminHiitop.Api.Migrations
{
    [DbContext(typeof(AdminHiitopDbContext))]
    partial class AdminHiitopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HexCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Dni")
                        .HasColumnType("longtext");

                    b.Property<string>("DocumentType")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NombreComercial")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("PickupKey")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("longtext");

                    b.Property<string>("Ruc")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.DocumentPrintFormat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("WidthMm")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DocumentPrintFormats");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanBeConverted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsCommercialDocument")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsProtected")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSunatDocument")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("RequiresCustomer")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RequiresRelatedDocument")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.DocumentTypePrintFormat", b =>
                {
                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentPrintFormatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("DocumentTypeId", "DocumentPrintFormatId");

                    b.HasIndex("DocumentPrintFormatId");

                    b.ToTable("DocumentTypePrintFormats");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsProtected")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("OrderStatuses");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ProductTypes");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.PurchaseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("PurchaseTypes");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Label")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.ShippingAgency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ShippingRate")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ShippingAgencies");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Sizes");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.UnitMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SunatCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("UnitMeasures");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPos")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("WarehouseTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int")
                        .HasColumnName("province_id");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int")
                        .HasColumnName("district_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("WarehouseTypeId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("DistrictId");

                    b.ToTable("warehouses");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.WarehouseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("WarehouseTypes");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Identity.Entities.ModelHasRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("ModelType")
                        .HasColumnType("varchar(255)");

                    b.HasKey("RoleId", "ModelId", "ModelType");

                    b.ToTable("ModelHasRoles");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Identity.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GuardName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "GuardName")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Identity.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GuardName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "GuardName")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Identity.Entities.RoleHasPermission", b =>
                {
                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("PermissionId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleHasPermissions");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Inventory.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("CollectionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("UnitMeasureId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasFilter("[Sku] IS NOT NULL");

                    b.HasIndex("UnitMeasureId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Inventory.Entities.ProductColor", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "ColorId");

                    b.HasIndex("ColorId");

                    b.ToTable("ProductColors");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Inventory.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Reserved")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Inventory.Entities.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NewQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("PreviousQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .HasColumnType("longtext");

                    b.Property<string>("Size")
                        .HasColumnType("longtext");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockId");

                    b.HasIndex("UserId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.DailySummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CdrContent")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SummaryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SummaryNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SunatCode")
                        .HasColumnType("int");

                    b.Property<string>("SunatDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("SunatNotesJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Ticket")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("XmlContent")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DailySummaries");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.DailySummaryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Correlativo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerDocNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerDocType")
                        .HasColumnType("longtext");

                    b.Property<int>("DailySummaryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DailySummaryId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("DailySummaryItems");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CdrContent")
                        .HasColumnType("longtext");

                    b.Property<int>("Correlativo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerDocNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerDocType")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FormOfPayment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("InvoiceSeriesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("MtoIgv")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("MtoImpVenta")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("MtoOperGravadas")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("NoteMotive")
                        .HasColumnType("longtext");

                    b.Property<string>("NoteMotiveDesc")
                        .HasColumnType("longtext");

                    b.Property<string>("Observations")
                        .HasColumnType("longtext");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RefDocDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RefDocNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("RefDocType")
                        .HasColumnType("longtext");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("SunatCode")
                        .HasColumnType("int");

                    b.Property<string>("SunatDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("SunatNotesJson")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorVenta")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("XmlContent")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FullNumber")
                        .IsUnique();

                    b.HasIndex("InvoiceSeriesId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("UserId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.InvoiceSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("NextNumber")
                        .HasColumnType("int");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Serie")
                        .IsUnique();

                    b.ToTable("InvoiceSeries");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("longtext");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DeliveryCost")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Dni")
                        .HasColumnType("longtext");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("longtext");

                    b.Property<int?>("DocumentPrintFormatId")
                        .HasColumnType("int");

                    b.Property<int?>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("GuideCarrierDocNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("GuideCarrierDocType")
                        .HasColumnType("longtext");

                    b.Property<string>("GuideCarrierName")
                        .HasColumnType("longtext");

                    b.Property<string>("GuideCdrContent")
                        .HasColumnType("longtext");

                    b.Property<int?>("GuideCorrelativo")
                        .HasColumnType("int");

                    b.Property<string>("GuideDestinationAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("GuideDestinationUbigeo")
                        .HasColumnType("longtext");

                    b.Property<string>("GuideDriverDocNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("GuideDriverDocType")
                        .HasColumnType("longtext");

                    b.Property<string>("GuideDriverLicense")
                        .HasColumnType("longtext");

                    b.Property<string>("GuideDriverName")
                        .HasColumnType("longtext");

                    b.Property<string>("GuideFullNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("GuideOriginAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("GuideOriginUbigeo")
                        .HasColumnType("longtext");

                    b.Property<int?>("GuidePackageCount")
                        .HasColumnType("int");

                    b.Property<string>("GuideRecipientDocNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("GuideRecipientDocType")
                        .HasColumnType("longtext");

                    b.Property<string>("GuideRecipientName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("GuideSentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GuideSeries")
                        .HasColumnType("longtext");

                    b.Property<string>("GuideStatus")
                        .HasColumnType("longtext");

                    b.Property<int?>("GuideSunatCode")
                        .HasColumnType("int");

                    b.Property<string>("GuideSunatDescription")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("GuideTotalWeight")
                        .HasColumnType("decimal(12,3)");

                    b.Property<DateTime?>("GuideTransferDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GuideTransferMode")
                        .HasColumnType("longtext");

                    b.Property<string>("GuideTransferReasonCode")
                        .HasColumnType("longtext");

                    b.Property<string>("GuideTransferReasonDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("GuideTransportCertificate")
                        .HasColumnType("longtext");

                    b.Property<string>("GuideVehiclePlate")
                        .HasColumnType("longtext");

                    b.Property<string>("GuideWeightUnit")
                        .HasColumnType("longtext");

                    b.Property<string>("GuideXmlContent")
                        .HasColumnType("longtext");

                    b.Property<bool>("NeedsReceipt")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Observations")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<int?>("PurchaseTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ShippingAgencyId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("DocumentPrintFormatId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("PurchaseTypeId");

                    b.HasIndex("ShippingAgencyId");

                    b.HasIndex("UserId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CollectionId")
                        .HasColumnType("int");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductKey")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("longtext");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("ColorId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("FixedPrice")
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.PromotionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("PromotionId");

                    b.ToTable("PromotionItems");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Branch")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerDepartment")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerDistrict")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerName")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerProvince")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerTaxId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeliveryType")
                        .HasColumnType("longtext");

                    b.Property<decimal>("DiscountGross")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("DiscountNet")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("DocumentTypeLabel")
                        .HasColumnType("longtext");

                    b.Property<string>("ImportBatch")
                        .HasColumnType("longtext");

                    b.Property<string>("ImportSource")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MovementType")
                        .HasColumnType("longtext");

                    b.Property<string>("PriceList")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("SaleDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Seller")
                        .HasColumnType("longtext");

                    b.Property<string>("SeriesNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("SeriesPrefix")
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalGross")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TotalNet")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TotalTax")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.SaleImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ImportedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ImportedRows")
                        .HasColumnType("int");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("SaleImports");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.SaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DiscountGross")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("DiscountName")
                        .HasColumnType("longtext");

                    b.Property<decimal>("DiscountNet")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("DiscountPct")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("ListPrice")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("Margin")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("MarginPct")
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("OtherAttributes")
                        .HasColumnType("longtext");

                    b.Property<string>("PackDetail")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductName")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductType")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalCostNet")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TotalGross")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TotalNet")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TotalTax")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("UnitCostNet")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("UnitGrossPrice")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("UnitNetPrice")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Variant")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.SunatSendLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CdrPath")
                        .HasColumnType("longtext");

                    b.Property<int>("Correlativo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("RequestXmlPath")
                        .HasColumnType("longtext");

                    b.Property<string>("ResponseCode")
                        .HasColumnType("longtext");

                    b.Property<string>("ResponseDescription")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("SunatSendLogs");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RememberToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.Customer", b =>
                {
                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.District", "District")
                        .WithMany("Customers")
                        .HasForeignKey("DistrictId");

                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.Province", "Province")
                        .WithMany("Customers")
                        .HasForeignKey("ProvinceId");

                    b.Navigation("District");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.District", b =>
                {
                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.DocumentTypePrintFormat", b =>
                {
                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.DocumentPrintFormat", "DocumentPrintFormat")
                        .WithMany("DocumentTypePrintFormats")
                        .HasForeignKey("DocumentPrintFormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.DocumentType", "DocumentType")
                        .WithMany("DocumentTypePrintFormats")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentPrintFormat");

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.Size", b =>
                {
                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.ProductType", "ProductType")
                        .WithMany("Sizes")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.Warehouse", b =>
                {
                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.WarehouseType", "WarehouseType")
                        .WithMany("Warehouses")
                        .HasForeignKey("WarehouseTypeId");

                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.Province", "Province")
                        .WithMany("Warehouses")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.District", "District")
                        .WithMany("Warehouses")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WarehouseType");
                    b.Navigation("Province");
                    b.Navigation("District");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Identity.Entities.ModelHasRole", b =>
                {
                    b.HasOne("AdminHiitop.Api.Domain.Identity.Entities.Role", "Role")
                        .WithMany("ModelRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Identity.Entities.RoleHasPermission", b =>
                {
                    b.HasOne("AdminHiitop.Api.Domain.Identity.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminHiitop.Api.Domain.Identity.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Inventory.Entities.Product", b =>
                {
                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.Collection", "Collection")
                        .WithMany("Products")
                        .HasForeignKey("CollectionId");

                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId");

                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.UnitMeasure", "UnitMeasure")
                        .WithMany("Products")
                        .HasForeignKey("UnitMeasureId");

                    b.Navigation("Collection");

                    b.Navigation("ProductType");

                    b.Navigation("UnitMeasure");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Inventory.Entities.ProductColor", b =>
                {
                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.Color", "Color")
                        .WithMany("ProductColors")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminHiitop.Api.Domain.Inventory.Entities.Product", "Product")
                        .WithMany("ProductColors")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Inventory.Entities.Stock", b =>
                {
                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.Color", "Color")
                        .WithMany("Stocks")
                        .HasForeignKey("ColorId");

                    b.HasOne("AdminHiitop.Api.Domain.Inventory.Entities.Product", "Product")
                        .WithMany("Stocks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.Warehouse", "Warehouse")
                        .WithMany("Stocks")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Inventory.Entities.StockMovement", b =>
                {
                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId");

                    b.HasOne("AdminHiitop.Api.Domain.Inventory.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminHiitop.Api.Domain.Inventory.Entities.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminHiitop.Api.Domain.Sales.Entities.User", "User")
                        .WithMany("StockMovements")
                        .HasForeignKey("UserId");

                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.Warehouse", "Warehouse")
                        .WithMany("StockMovements")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Product");

                    b.Navigation("Stock");

                    b.Navigation("User");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.DailySummaryItem", b =>
                {
                    b.HasOne("AdminHiitop.Api.Domain.Sales.Entities.DailySummary", "DailySummary")
                        .WithMany("Items")
                        .HasForeignKey("DailySummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminHiitop.Api.Domain.Sales.Entities.Invoice", "Invoice")
                        .WithMany("DailySummaryItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailySummary");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.Invoice", b =>
                {
                    b.HasOne("AdminHiitop.Api.Domain.Sales.Entities.InvoiceSeries", "InvoiceSeries")
                        .WithMany("Invoices")
                        .HasForeignKey("InvoiceSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminHiitop.Api.Domain.Sales.Entities.Order", "Order")
                        .WithMany("Invoices")
                        .HasForeignKey("OrderId");

                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("Invoices")
                        .HasForeignKey("PaymentMethodId");

                    b.HasOne("AdminHiitop.Api.Domain.Sales.Entities.User", "User")
                        .WithMany("Invoices")
                        .HasForeignKey("UserId");

                    b.Navigation("InvoiceSeries");

                    b.Navigation("Order");

                    b.Navigation("PaymentMethod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.Order", b =>
                {
                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId");

                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.District", "District")
                        .WithMany("Orders")
                        .HasForeignKey("DistrictId");

                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.DocumentPrintFormat", "DocumentPrintFormat")
                        .WithMany("Orders")
                        .HasForeignKey("DocumentPrintFormatId");

                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.DocumentType", "DocumentType")
                        .WithMany("Orders")
                        .HasForeignKey("DocumentTypeId");

                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.OrderStatus", "OrderStatus")
                        .WithMany("Orders")
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.Province", "Province")
                        .WithMany("Orders")
                        .HasForeignKey("ProvinceId");

                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.PurchaseType", "PurchaseType")
                        .WithMany("Orders")
                        .HasForeignKey("PurchaseTypeId");

                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.ShippingAgency", "ShippingAgency")
                        .WithMany("Orders")
                        .HasForeignKey("ShippingAgencyId");

                    b.HasOne("AdminHiitop.Api.Domain.Sales.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.Warehouse", "Warehouse")
                        .WithMany("Orders")
                        .HasForeignKey("WarehouseId");

                    b.Navigation("Customer");

                    b.Navigation("District");

                    b.Navigation("DocumentPrintFormat");

                    b.Navigation("DocumentType");

                    b.Navigation("OrderStatus");

                    b.Navigation("Province");

                    b.Navigation("PurchaseType");

                    b.Navigation("ShippingAgency");

                    b.Navigation("User");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.OrderItem", b =>
                {
                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.Collection", "Collection")
                        .WithMany("OrderItems")
                        .HasForeignKey("CollectionId");

                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.Color", "Color")
                        .WithMany("OrderItems")
                        .HasForeignKey("ColorId");

                    b.HasOne("AdminHiitop.Api.Domain.Sales.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminHiitop.Api.Domain.Inventory.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Collection");

                    b.Navigation("Color");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.PromotionItem", b =>
                {
                    b.HasOne("AdminHiitop.Api.Domain.Inventory.Entities.Product", "Product")
                        .WithMany("PromotionItems")
                        .HasForeignKey("ProductId");

                    b.HasOne("AdminHiitop.Api.Domain.Catalog.Entities.ProductType", "ProductType")
                        .WithMany("PromotionItems")
                        .HasForeignKey("ProductTypeId");

                    b.HasOne("AdminHiitop.Api.Domain.Sales.Entities.Promotion", "Promotion")
                        .WithMany("Items")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductType");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.Sale", b =>
                {
                    b.HasOne("AdminHiitop.Api.Domain.Sales.Entities.User", "User")
                        .WithMany("Sales")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.SaleItem", b =>
                {
                    b.HasOne("AdminHiitop.Api.Domain.Sales.Entities.Sale", "Sale")
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.SunatSendLog", b =>
                {
                    b.HasOne("AdminHiitop.Api.Domain.Sales.Entities.Invoice", "Invoice")
                        .WithMany("SunatSendLogs")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.Collection", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.Color", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ProductColors");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.District", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Orders");

                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.DocumentPrintFormat", b =>
                {
                    b.Navigation("DocumentTypePrintFormats");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.DocumentType", b =>
                {
                    b.Navigation("DocumentTypePrintFormats");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.PaymentMethod", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.ProductType", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("PromotionItems");

                    b.Navigation("Sizes");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.Province", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Districts");

                    b.Navigation("Orders");

                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.PurchaseType", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.ShippingAgency", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.UnitMeasure", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.Warehouse", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("StockMovements");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Catalog.Entities.WarehouseType", b =>
                {
                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Identity.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Identity.Entities.Role", b =>
                {
                    b.Navigation("ModelRoles");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Inventory.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ProductColors");

                    b.Navigation("PromotionItems");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.DailySummary", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.Invoice", b =>
                {
                    b.Navigation("DailySummaryItems");

                    b.Navigation("SunatSendLogs");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.InvoiceSeries", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.Order", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.Promotion", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.Sale", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AdminHiitop.Api.Domain.Sales.Entities.User", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Orders");

                    b.Navigation("Sales");

                    b.Navigation("StockMovements");
                });
#pragma warning restore 612, 618
        }
    }
}
